fix: PATH for zsh
alissa-tung/glean pull request #1
Opened 2023-11-02 14:42 UTC by timechess

2023-11-09 12:46 UTC, alissa-tung requested changes
Thank you! here are some suggestions

2023-11-09 12:47 UTC, alissa-tung commented
You can test the changes by using `go build main.go` in the project root directory

2023-11-09 12:49 UTC, alissa-tung commented on glean/elan.go
> +
And you can also add some thing like

```sh
########
# begin @generated by glean
# end @generated by glean
########
```

2023-11-09 17:46 UTC, timechess commented
Done it. It works on my Ubuntu. Hopefully it will also work on Mac.

2023-11-12 04:37 UTC, alissa-tung requested changes

2023-11-12 04:37 UTC, alissa-tung commented on glean/elan.go
> +		zpfPath := os.Getenv("HOME") + "/.zprofile"
Could you please use join for paths here?

2023-11-12 04:37 UTC, alissa-tung commented on glean/elan.go
> +		zshcmd := exec.Command("/bin/sh","-c", "echo" + zshText+ ">>" + zpfPath)
It would be easier to just use append method for file

2023-11-12 07:08 UTC, merged